### ISSUE TITLE
Problemas para proyecto

### ISSUE THREAD

**Issue by kiberamos** [wcadena/MavenLibriotecaTrabajoFinal#1]
- Pantalla mejorada visualmente

- Impresion de Datos Clara

- Cambio de ListView por tableview

**Comment by wcadena** [comment]
se realiza primer cambio por # f82dead298e4c4ce109f71894022a9642095266a

**Comment by wcadena** [comment]
#f82dead298e4c4ce109f71894022a9642095266a

**Comment by wcadena** [comment]
se realiza cambio de impresion de dats de lista a tabla # 3caf4e5

**Comment by wcadena** [comment]
se crea validacion con  c353d46
